name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Cache Yarn cache
        uses: actions/cache@v2
        with:
          path: ~/.yarn
          key: ${{ runner.OS }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.OS }}-yarn-

      - name: Install Dependencies
        run: yarn install --frozen-lockfile

      - name: Check Linting
        run: yarn lint

      - name: Run Tests
        run: yarn test
